### ISSUE TITLE
Readme states that `setup` is not required although it is

### ISSUE THREAD

**Issue by smjonas** [mizlan/delimited.nvim#1]
Hi, nice plugin. I noticed that you stated in the readme that `setup` (e.g. using `opts` in lazyvim) is not required for the default usage. This is wrong, since without calling `setup`, the highlights won't be defined. This tripped me up while trying to get the plugin to work. Can you either correct that in the readme or add a check in the code to assert that `setup` has been called? Thanks.

**Comment by mizlan** [comment]
My apologies, you are absolutely right. I can change the README.
